# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import currency_pb2 as currency__pb2


class CurrencyExchangeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getRate = channel.unary_stream(
        '/helloworld.CurrencyExchange/getRate',
        request_serializer=currency__pb2.RateRequest.SerializeToString,
        response_deserializer=currency__pb2.Rate.FromString,
        )


class CurrencyExchangeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getRate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CurrencyExchangeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getRate': grpc.unary_stream_rpc_method_handler(
          servicer.getRate,
          request_deserializer=currency__pb2.RateRequest.FromString,
          response_serializer=currency__pb2.Rate.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helloworld.CurrencyExchange', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
