# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: currency.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='currency.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=_b('\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x0e\x63urrency.proto\x12\nhelloworld\"c\n\x0bRateRequest\x12*\n\x0c\x63urrencyFrom\x18\x01 \x01(\x0e\x32\x14.helloworld.Currency\x12(\n\ncurrencyTo\x18\x02 \x01(\x0e\x32\x14.helloworld.Currency\"\x15\n\x04Rate\x12\r\n\x05value\x18\x01 \x01(\x01*%\n\x08\x43urrency\x12\x07\n\x03\x45UR\x10\x00\x12\x07\n\x03USD\x10\x01\x12\x07\n\x03PLN\x10\x02\x32L\n\x10\x43urrencyExchange\x12\x38\n\x07getRate\x12\x17.helloworld.RateRequest\x1a\x10.helloworld.Rate\"\x00\x30\x01\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)

_CURRENCY = _descriptor.EnumDescriptor(
  name='Currency',
  full_name='helloworld.Currency',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EUR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=154,
  serialized_end=191,
)
_sym_db.RegisterEnumDescriptor(_CURRENCY)

Currency = enum_type_wrapper.EnumTypeWrapper(_CURRENCY)
EUR = 0
USD = 1
PLN = 2



_RATEREQUEST = _descriptor.Descriptor(
  name='RateRequest',
  full_name='helloworld.RateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currencyFrom', full_name='helloworld.RateRequest.currencyFrom', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currencyTo', full_name='helloworld.RateRequest.currencyTo', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=129,
)


_RATE = _descriptor.Descriptor(
  name='Rate',
  full_name='helloworld.Rate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='helloworld.Rate.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=152,
)

_RATEREQUEST.fields_by_name['currencyFrom'].enum_type = _CURRENCY
_RATEREQUEST.fields_by_name['currencyTo'].enum_type = _CURRENCY
DESCRIPTOR.message_types_by_name['RateRequest'] = _RATEREQUEST
DESCRIPTOR.message_types_by_name['Rate'] = _RATE
DESCRIPTOR.enum_types_by_name['Currency'] = _CURRENCY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RateRequest = _reflection.GeneratedProtocolMessageType('RateRequest', (_message.Message,), dict(
  DESCRIPTOR = _RATEREQUEST,
  __module__ = 'currency_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.RateRequest)
  ))
_sym_db.RegisterMessage(RateRequest)

Rate = _reflection.GeneratedProtocolMessageType('Rate', (_message.Message,), dict(
  DESCRIPTOR = _RATE,
  __module__ = 'currency_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Rate)
  ))
_sym_db.RegisterMessage(Rate)


DESCRIPTOR._options = None

_CURRENCYEXCHANGE = _descriptor.ServiceDescriptor(
  name='CurrencyExchange',
  full_name='helloworld.CurrencyExchange',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=193,
  serialized_end=269,
  methods=[
  _descriptor.MethodDescriptor(
    name='getRate',
    full_name='helloworld.CurrencyExchange.getRate',
    index=0,
    containing_service=None,
    input_type=_RATEREQUEST,
    output_type=_RATE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CURRENCYEXCHANGE)

DESCRIPTOR.services_by_name['CurrencyExchange'] = _CURRENCYEXCHANGE

# @@protoc_insertion_point(module_scope)
